### ISSUE TITLE
是否需要新建ftl文件或目录

### ISSUE THREAD

**Issue by leonardocsc** [dongfangshangren/Zblog#18]
`当想保存文章或链接信息时，总是在freemarkerutil处报初始化异常，后调试发现`URL uri = FreeMarkerUtils.class.getResource("ftl");
			config.setDirectoryForTemplateLoading(new File(uri.toURI()));`url为空导致。该如何解决的？是否需要新建ftl文件？

**Comment by dongfangshangren** [comment]
详见https://github.com/dongfangshangren/Zblog/issues/7
