### ISSUE TITLE
恶意登录检测问题

### ISSUE THREAD

**Issue by terwer** [dongfangshangren/Zblog#2]
LoginFormValidator.java里面的判断
//    if(!guard.equals(form.getGuard())){
//      result.put("msg", "请不要尝试登录了!");
//    }else

我没有进行非法操作，但还是提示“请不要尝试登录了”，这个判断的依据是什么，guard是在什么时候注入的?

**Comment by dongfangshangren** [comment]
因为后台未使用验证码登录，为防止暴力破解，在后台登录，请带上登录参数，如http://www.yourdomain/backend/login?guard=no，其中‘no’值在https://github.com/dongfangshangren/Zblog/blob/master/src/main/resources/config/spring-service.xml文件中配置

**Comment by ststring** [comment]
@dongfangshangren 建议登录弄个ecache，得到ip统计单位时间重试次数来防止暴力破解

**Comment by popotans** [comment]
终于明白guard=no 这个东西了，
