### ISSUE TITLE
库已建好,但是数据表脚本好像没有！没法继续

### ISSUE THREAD

**Issue by onsoul** [dongfangshangren/Zblog#23]
DEBUG 2016-07-15 14:53:28,137 [http-bio-8080-exec-5] com.zblog.core.dal.mapper.PostMapper.list ==>  Preparing: select count(*) from ( select id from post p where p.type=? order by p.createTime desc ) _temp_ 
DEBUG 2016-07-15 14:53:28,158 [http-bio-8080-exec-5] com.zblog.core.util.BeanPropertyUtils can't found field mappedStatement in class class org.apache.ibatis.executor.statement.PreparedStatementHandler
DEBUG 2016-07-15 14:53:28,159 [http-bio-8080-exec-5] com.zblog.core.dal.mapper.PostMapper.list ==> Parameters: post(String)
ERROR 2016-07-15 14:53:28,162 [http-bio-8080-exec-5] com.zblog.core.plugin.PageInterceptor can't get count Table 'zblog.post' doesn't exist
DEBUG 2016-07-15 14:53:28,165 [http-bio-8080-exec-5] com.zblog.core.dal.mapper.PostMapper.list ==>  Preparing: select id from post p where p.type=? order by p.createTime desc limit 0,10 
DEBUG 2016-07-15 14:53:28,166 [http-bio-8080-exec-5] com.zblog.core.dal.mapper.PostMapper.list ==> Parameters: post(String)
ERROR 2016-07-15 14:53:28,211 [http-bio-8080-exec-5] com.zblog.web.filter.LoginFilter error happend
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'zblog.post' doesn't exist

**Comment by dongfangshangren** [comment]
项目目录项目zblog.sql就是
