### ISSUE TITLE
putIfAbsent的引用不明确

### ISSUE THREAD

**Issue by LMFName** [dongfangshangren/Zblog#31]
\zblog\core\wordpress\WordPressReader.java Error:(93, 18) java: 对putIfAbsent的引用不明确
  java.util.HashMap 中的方法 putIfAbsent(K,V) 和 com.zblog.core.plugin.MapContainer 中的方法 <T>putIfAbsent(java.lang.String,T) 都匹配

**Comment by dongfangshangren** [comment]
see https://github.com/dongfangshangren/Zblog/issues/14
