### ISSUE TITLE
部署文档

### ISSUE THREAD

**Issue by openbytes** [dongfangshangren/Zblog#39]
你好!我不是java 程序员,这个需要怎么部署,有文档嘛?

**Comment by zhouit** [comment]
先在mysql里面导入zblog.sql文件

git clone https://github.com/dongfangshangren/Zblog.git
cd Zblog
编辑src/main/resources/jdbc.properties
使用自己的mysqlip地址账号密码
mvn clean package -Dmaven.test.skip=true
cd target
有一个war文件部署到tomcat就行了

**Comment by openbytes** [comment]
感谢小帅哥!!!
